version: '3.4'

services:
  db:
    image: fandradetecinfo/webapi-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile    
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: web_api
    ports:
      - "3306:3306"
    networks:
      - webapi-network

  webapi:
    image: fandradetecinfo/webapi-api
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:80"
    links:
      - db
    depends_on:
      - db
    networks:
      - webapi-network

networks:
  webapi-network:
    driver: bridge
      
