version: '3.4'

services:
  db:
    image: mcoc-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: webapi_user
      MYSQL_PASSWORD: webapi_user
      MYSQL_DATABASE: webapi
    ports:
      - "3306:3306"
    networks:
      - webapi-network

  webapi:
    image: mcoc-web-api
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5000:80"
    links:
      - db
    depends_on:
      - db
    networks:
      - webapi-network

networks:
  webapi-network:
        driver: nat
      
