CREATE TABLE  IF NOT EXISTS `web_users` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`Login` VARCHAR(50) UNIQUE NOT NULL,
	`AccessKey` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`ID`)
)
ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
